# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-22 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastpayment',
            field=models.CharField(default='90.892.00', max_length=30),
        ),
    ]
