# Generated by Django 3.0.6 on 2020-07-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_user_lastpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authcode',
            field=models.CharField(default='9898', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
